language: go

services:
- docker

jobs:
  include:
  - name: build-binaries
    stage: build
    script: make container-run/all
  - name: deploy-container-image-latest
    stage: deploy
    script: make container-image/push
  - name: deploy-container-image-tagged
    stage: deploy
    script: make container-image/push VERSION=${TRAVIS_TAG} CONTAINER_IMAGE_VERSION=${TRAVIS_TAG}
    on:
      tags: true

notifications:
  email:
    on_success: change
    on_failure: change